### ISSUE TITLE
KeyError: 'CHARGE_STATUS'

### ISSUE THREAD

**Issue by andrew-lozoya** [mbevand/owlet_monitor#10]
Does not seem to like something!

Logging in
Auth token XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Getting DSN
Found Owlet monitor device serial number XXXXXXXXXXXXXXXXXX
Traceback (most recent call last):
  File "/Users/XXXXX/Desktop/owlet_monitor-master/./owlet_monitor.py", line 198, in <module>
    main()
  File "/Users/XXXXX/Desktop/owlet_monitor-master/./owlet_monitor.py", line 192, in main
    loop()
  File "/Users/XXXXX/Desktop/owlet_monitor-master/./owlet_monitor.py", line 183, in loop
    record_vitals(prop)
  File "/Users/XXXXX/Desktop/owlet_monitor-master/./owlet_monitor.py", line 151, in record_vitals
    charge_status = p['CHARGE_STATUS']['value']
KeyError: 'CHARGE_STATUS'

**Comment by andrew-lozoya** [comment]
Looks like the properties have changed

        "property": {
            "type": "Property",
            "name": "REAL_TIME_VITALS",
            "base_type": "string",
            "read_only": true,
            "direction": "output",
            "scope": "user",
            "data_updated_at": "2021-05-19T20:32:38Z",
            "key": XXXXXXXXXX,
            "device_key": XXXXXXXXXX,
            "product_name": "Owlet Baby Monitors",
            "track_only_changes": false,
            "display_name": "Real-Time Vitals",
            "host_sw_version": false,
            "time_series": false,
            "derived": false,
            "app_type": null,
            "recipe": null,
            "value": "{\"ox\":97,\"hr\":152,\"mv\":3,\"sc\":2,\"st\":0,\"bso\":1,\"bat\":100,\"btt\":974,\"chg\":0,\"aps\":0,\"alrt\":0,\"ota\":0,\"srf\":1,\"rsi\":69}",
            "denied_roles": [],
            "ack_enabled": false,
            "retention_days": 30,
            "ack_status": null,
            "ack_message": null,
            "acked_at": null
        }
    },
